### ISSUE TITLE
Ignore OSX files

### ISSUE THREAD

**Issue by MrFusion42** [alfredoBorboa/swapi#1]
Cool project!

The repo has some OSX-specific files (`.DS_Store`) that probably shouldn't be versioned.

This site is very helpful for generating the proper `.gitignore` file, keeping unwanted files out of your repo: https://www.gitignore.io/ (try adding OSX to the list)

**Comment by alfredoBorboa** [comment]
Thanks for the heads up! I've generated and added the .gitignore file. OS specific files shouldn't be a problem now. Great tool BTW! Hadn't heard of it.
